#!/usr/bin/env python3


categories = {
    "fan": "Fan",
    "massage": "Massage",
    "lightbulb": "Light Bulb",
    "mixer": "Mixer",
    "flatiron": "Flat Iron",
    "microwave": "Microwave",
    "ledlight": "Ledlight",
    "iron": "Iron",
    "kettle": "Kettle",
    "cablereceiver": "Cable Receiver",
    "benchgrinder": "Bench Grinder",
    "drillingmachine": "Drilling Machine",
    "laserprinter": "Laser Printer",
    "washingmachine": "Washing Machine",
    "halogen": "Halogen",
    "gameconsole": "Game Console",
    "ricecooker": "Rice Cooker",
    "hairdryer": "Hairdryer",
    "mosquitorepellent": "Mosquito Repellent",
    "charger": "Charger",
    "airpump": "Air Pump",
    "shredder": "Shredder",
    "toaster": "Toaster",
    "coffeemachine": "Coffee Machine",
    "treadmill": "Treadmill",
    "powersupply": "Power Supple",
    "waterheater": "Water Heater",
    "tv": "TV",
    "laptop": "Laptop",
    "stove": "Stove",
    "networkswitch": "Network Switch",
    "vacuumcleaner": "Vaccum Cleaner",
    "fridge": "Fridge",
    "desktoppc": "Desktop PC",
    "fanheater": "Fan Heater",
    "monitor": "Monitor",
    "multitool": "Multitool",
    "hifi": "High Fidelity",
    "solderingiron": "Soldering Iron",
    "halogenfluter": "Halogen Fluter",
    "ac": "AC",
    "deepfryer": "Deep Fryer",
    "shoewarmer": "Shoe Warmer",
    "juicemaker": "Juice Maker",
    "cfl": "Compact Fluorescent Lamp",
    "projector": "Projector",
    "sewingmachine": "Sewing Machine",
    "sandwichmaker": "Sandwich Maker",
    "waterpump": "Water Pump",
    "desoldering": "Desoldering",
    "kitchenhood": "Kitchen Hood",
    "heater": "Heater",
    "guitaramp": "Guitar Amplifier",
    "cablemodem": "Cable Modem",
    "jigsaw": "Jigsaw",
}
